# Base configs
baseurl: ""

# UI configs
title: "Jay Chopra"
author: "Jay Chopra"
about: "creatio ex nihilo"
social_urls:
  facebook: "https://www.facebook.com/profile.php?id=100008044485467"
  twitter: ""
  instagram: "https://www.instagram.com/im_jay_7"
